# Generated by Django 2.0.2 on 2018-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0005_auto_20151122_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plantilla',
            field=models.IntegerField(choices=[(1, 'Predeterminado'), (2, 'Clasico')], default=1),
        ),
    ]
