# Generated by Django 2.0.6 on 2018-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('number', models.IntegerField(default=0, verbose_name='Numero de lista')),
                ('type', models.CharField(choices=[('1', 'Monografía'), ('2', 'Biografia'), ('3', 'Mapa')], max_length=1, verbose_name='Tipo de producto')),
                ('active', models.BooleanField(default=True, verbose_name='Activar para listar')),
            ],
        ),
    ]
