# Generated by Django 2.0.6 on 2019-09-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Varios', '0002_auto_20190910_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listed',
            name='provider',
            field=models.CharField(choices=[('1', 'SUN RISE'), ('2', 'RAF'), ('3', 'BOB')], max_length=1, verbose_name='Proveedor del producto'),
        ),
    ]
