# Generated by Django 2.0.6 on 2018-07-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0005_auto_20180715_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Venta.SalesAccount'),
        ),
    ]
