# Generated by Django 2.0.6 on 2018-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0006_auto_20180718_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
